version: "3.3"

services:
  real-time-todo:
    container_name: real-time-todo
    build: ./
    volumes:
      - ".:/app"
      - "/app/node_modules"
    expose:
      - "8080"
    environment:
         VIRTUAL_HOST: real-time-todo.s-website.ga
    networks:
      - nginx_main
      - backend

networks:
  nginx_main:
    external: true
  backend:
    external: true
