version: "3.3"

services:
  real-time-todo:
    env_file: ../secrets/real-time-todo/real-time-todo.env
    container_name: real-time-todo
    build: ./app
    volumes:
      - "./app:/app"
      - "/app/node_modules"
    expose:
      - "8080"
    networks:
      - nginx_main
      - backend

networks:
  nginx_main:
    external: true
  backend:
    external: true
